import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import CodeEditor from '../components/CodeEditorMirror'
import { javascript } from "@codemirror/lang-javascript";
import SubmitAnswer from '@components/Submit'

export default function Home() {
  // const onChange = useCallback((value, viewUpdate) => {
  //   console.log('value:', value);
  // }, []);
  return (
    <>
      <Head>
        <title>Code Runner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dinoRunner16_16.ico" />
      </Head>
      {/* <h2 className='navbar'>Welcome to CodeRunner 🦖!</h2> */}
      <main className="flex justify-between items-center px-5 min-h-screen">
        <aside className="prose  ">
          <h2>
            217. Contains Duplicate
          </h2>
          <p>Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.</p>

          <div id="examples" className='examples '> 
            <div>Example 1</div>
            <code className='bg-gray-200'>
              Input: nums = [1,2,3,1]
              Output: true
            </code>

            <div>Example 2</div>
            <code className='bg-gray-200'>
              Input: nums = [1,2,3,4]
              Output: false
            </code>

            <div>Example 2</div>
            <code className='bg-gray-200'>
              Input: nums = [1,1,1,3,3,4,3,2,4,2]
              Output: true
            </code>
          </div>

          <div id="constrains">
            <h4>Constrains </h4>
            <ul>
              <li>{ "1 <= nums.length <= 105" }</li>
              <li>{ "-109 <= nums[i] <= 109" }</li>
            </ul>
          </div>
        </aside>
        <div id="CodeEditor">
          <CodeEditor />
          {/* <SubmitAnswer /> */}
          <div id="inputs" className='flex justify-evenly p-5'>
            <div className='btn btn-ghost grow '>Console</div>
            <div className='btn btn-secondary'>Run</div>
            <div className='btn btn-primary'>Submit Answer</div>
          </div>
        </div>
      </main>
    </>
  )
}
