import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import CodeEditorWindow from '@components/CodeEditorWindow';
import SubmitAnswer from '@components/Submit';
import TestSucces from '@components/TestSucces'
import TestFailed from '@components/TestFailed'
import { useCallback, useState } from 'react';
import axios from 'axios';

export default function Home() {
  const [code, setCode] = useState("");
  const [tests, setTests] = useState<boolean[]>();
  const url = "http://localhost:80";

  const submitAnswer = (e: MouseEvent<HTMLDivElement, MouseEvent>) => {
    axios
      .post(url, { code })
      .then(data => {
        console.log(data.data.testCaseResults);
        setTests(data.data.testCaseResults);
      });
  };
  
  return (
    <>
      <Head>
        <title>Code Runner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dinoRunner16_16.ico" />
      </Head>
      {/* <h2 className='navbar'>Welcome to CodeRunner 🦖!</h2> */}
      <nav className='navbar flex justify-between px-4'>
        <div>logo </div>
        <div> controls </div>
        <div>login</div>
      </nav>
      <main className="flex h-screen w-full justify-between px-4 ">
        <aside className="prose h-[90vh] w-full ">
          <div id="problem" className='h-full flex flex-col overflow-y-auto '>
            <h2>
              217. Contains Duplicate
            </h2>
            <p>Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.</p>

            <div id="examples" className='examples bg-gray-200 p-2'>
              <div>Example 1</div>
              <code className='bg-gray-200'>
                Input: nums = [1,2,3,1]
                Output: true
              </code>

              <div>Example 2</div>
              <code className='bg-gray-200'>
                Input: nums = [1,2,3,4]
                Output: false
              </code>

              <div>Example 3</div>
              <code className='bg-gray-200'>
                Input: nums = [1,1,1,3,3,4,3,2,4,2]
                Output: true
              </code>
            </div>

            <div id="constrains">
              <h4>Constrains </h4>
              <ul>
                <li>{"1 <= nums.length <= 105"}</li>
                <li>{"-109 <= nums[i] <= 109"}</li>
              </ul>
            </div>

          </div>
        </aside>
        <div id="resizeBar" className='h-full flex items-center bg-gray-400 hover:bg-blue-500
        cursor-col-resize'>...</div>
        <div id="CodeEditor" className='flex flex-col w-full'>
          <CodeEditorWindow  />
          <div id="inputs" className='flex justify-evenly p-5'>
            <div className='btn btn-ghost grow '>Console</div>
            <div className='btn btn-secondary'>Run</div>
            <div className='btn btn-primary' onClick={submitAnswer} >Submit Answer</div>
          </div>
          <div id="results" className='flex'>
            { tests?.map((test, i) => {
              if (test === true) {
                return (<div key={i}><TestSucces /></div>)
              }
              return (<div key={i}><TestFailed /></div>)})}
          </div>
        </div>
      </main>
    </>
  )
}
